spring:
  application:
    name: CONFIG-SERVER-DEV
 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Harry1d/microservicetest
          clone-on-start: true
          
          
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
          
